version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: easycart-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: easycart
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - easycart-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: easycart-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - easycart-network

volumes:
  postgres-data:
  pgadmin-data:

networks:
  easycart-network:
    driver: bridge
